### ISSUE TITLE
Image appears in Foreground

### ISSUE THREAD

**Issue by metalshreds** [Ultimatum22/MMM-RandomBackground#3]
Great module! exactly what I was looking for! I am having one problem though. The image appears in the foreground above all other modules and makes the text hard to read.  Also, I am not sure if it makes a difference but I had to put it  in position  'fullscreen_above' because otherwise It only shows about an inch of the background on the top left corner of the display. Thanks!

**Comment by Ultimatum22** [comment]
Are you sure it's on the foreground because then you shouldn't see any text. I modified my own version with darker text colors, will add that if I find some time.

Mine still works with fullscreen_below. Do you see any errors? Fullscreen_above forces it above all the other modules, so if you have no other modules that shouldn't be an issue.

**Comment by metalshreds** [comment]
I made the opacity 50% 
This is what I see when I set the position to "below"
![below](https://user-images.githubusercontent.com/3744553/29276152-4bd66ec8-80d3-11e7-93e5-ee9872d221c6.jpg)
And when I set it to above, you can see it is on the foreground because it overlaps with the image of the dog in the middle and gives texture to the text
![above](https://user-images.githubusercontent.com/3744553/29276151-4bd4ba24-80d3-11e7-8e1b-d0c88440b1a5.jpg)

I only see the following errors below
```
Launching application.
Loaded 4 images.
Error: The given image is not a JPEG and thus unsupported right now.
Error: The Exif data is not valid.
Error: No Exif segment found in the given image.
```

**Comment by metalshreds** [comment]
quick update, I was able to fix this by setting the position of the module to "fullscreen_below" so it lays below all other modules, and then changing position property of CSS to "fixed" so it is relative to the browser window. I am no css expert but this worked for me. Thanks again for creating the module! :) 

![rbg](https://user-images.githubusercontent.com/3744553/29697825-1788f748-8917-11e7-83d1-1560715dd724.jpg)
