### ISSUE TITLE
Nothing diplayed

### ISSUE THREAD

**Issue by Arkoxs** [Ultimatum22/MMM-RandomBackground#6]
I've added a flash drive with jpg photos and mounted them on "/photos".
After that installed MMM-RandomBackground and ran the "npm install' no errors.

After adding the module to the config.js nothing was displayed. I've tried different locations but then the MagicMirror 2 just stops loading.

Is there any logging so I can see whats going wrong?

**Comment by Ultimatum22** [comment]
Did you mount them on /photos on root or in MMM-RandomBackground folder? No additional logging except the count of loaded files (I believe that log line is still present...)

**Comment by Arkoxs** [comment]
As suggested in an earlier post I've mounted the folder in root.

> Ultimatum22 commented: Create a folder called photos in the root directory. Put photos or directectories with photos in there and they should load automatically

**Comment by Snawe** [comment]
I have the same problem. created a folder called "photos" in root. nothing. everything is black

**Comment by Ultimatum22** [comment]
@Arkoxs The root of this module or root of MagicMirror? You should create the folder it in MMM-RandomBackground. I will commit a change that the folder will be created automatically.

**Comment by Arkoxs** [comment]
Great, that will be less confusing.
"There can only be one root /"

**Comment by Ultimatum22** [comment]
Do you have it working?

**Comment by Arkoxs** [comment]
Yes, after mounting my USB Flashdrive to ~/MagicMirror/modules/MMM-RandomBackground/photos and changing the position back to 'fullscreen_below', the images are displayed.

Thanks.

**Comment by Arkoxs** [comment]
My current config:
{
module : 'MMM-RandomBackground',
position : 'fullscreen_below', // Any region but this one makes the most sense
config : {
animationSpeed :	1 * 1000,		//	How fast the new image fades into the old one (in milliseconds). A higher value means a slower animation. Default is 1000 ms.
updateInterval :	1 * 60 * 1000,	//	How often a new photo is displayed. Default is 10 minutes.
showAdditionalInfo :	false,		//	Show image meta info. Default is false.
randomOrder :			true,		//	Display images in random order. Default is true.
opacity :	0.5,					//	Opacity of the background. Ranged 0.0 to 1.0. Default is 1.0.
//photoDirectories :					//	[Functionality not yet implemented]
}
}

**Comment by Ultimatum22** [comment]
Great that is works. You have any other issues?

**Comment by Arkoxs** [comment]
Not sure what causes it but metadata and image orientation are not processed.
Some of the images are displayed upside down and if I set showAdditionalInfo to true then at the bottom of the screen the text "Picture taken by Unknown" then all zero's for date and time.

**Comment by Arkoxs** [comment]
I'll create a new issue for those problems.
